### ISSUE TITLE
Request:  support for JS in C++ 

### ISSUE THREAD

**Issue by drschwabe** [DariusCorvus/tree-sitter-language-injection.nvim#1]
Hi, appreciate the simplicity of your plugin compared to say the other closest thing maybe otter

Apologies however, I'm not too well versed in Lua or TreeSitter so I would just like to put in a request for ability to highlight JavaScript from a C++ multiline string or maybe a general suggestion on how to go about writing it myself. 

Details/example: 

https://neovim.discourse.group/t/highlight-javascript-in-a-c-file-w-treesitter/4681

**Comment by drschwabe** [comment]
Correct the js( part isn't valid JavaScript but it is valid C++ 

Basically in C++ you can set your own delimiter name after the `R"` when opening a multiline string.    In this case I just labeled it JS but you can make any arbitrary label ie- "xxx" or whatever:  

```
  qjsutil::runJs(context, R"xxx(
    lib.loadSounds()
    startscreen.setup()
    gameplay.setup()  
  )xxx"); 
```

in this case the label chosen needs to be also in the C++ multiline closing

it might be cool if we agreed on a standard `R"js(` here to denote / trigger your language injection since its pretty explicit (and could be used if someone wanted another language supported in C++ ex `R"ruby(`   

But if thats complicated then am certainly AOK with an inline comment.   
Thanks for looking at the issue!

**Comment by DariusCorvus** [comment]
It looks like it is already implemented in the newest Versions of the Treesitter Parser for cpp.

I tried it with js()js and ts()ts and it injected the highlighting correctly.
![image](https://github.com/user-attachments/assets/46fae92b-a4e8-4aa2-a6ba-df0faef6e227)

can you verify it for yourself? try it with newest versions of nvim and treesitter.

please report to me if it works for you, when not i'm happy to implement it for you.

**Comment by DariusCorvus** [comment]
it looks like the issue is solved for you.
